export const DIFFICULTY_META = {
  hard: {
    title: "קורסים קשים",
    label: "קשה",
    description: "מסגרת אדומה לקורסים שמרגישים כבדים יותר או שהמבחן בהם נחשב קשה.",
  },
  medium: {
    title: "קורסים בינוניים",
    label: "בינוני",
    description: "מסגרת צהובה לקורסים שאפשר לעבור יפה עם קצב עבודה טוב לאורך הדרך.",
  },
  easy: {
    title: "קורסים קלים",
    label: "קל",
    description: "מסגרת ירוקה לקורסים שנחשבים קלים יחסית או נוחים יותר לניהול.",
  },
};

export const EFFORT_FILTERS = {
  all: "הכל",
  high: "דורש השקעה שוטפת",
  low: "קליל יותר במהלך הסמסטר",
};

export const SORT_OPTIONS = {
  difficulty: "לפי דרגת קושי",
  name: "לפי א׳-ב׳",
  effort: "לפי רמת השקעה",
};

export const SYSTEM_PLANNER_TIPS = [
  "מומלץ להתפטר מהאנגלית כמה שיותר מוקדם.",
  "אם נכשלתם בקורס שחוסם קורסים אחרים, קחו אותו שוב מוקדם ככל הניתן.",
  "בקורסי רשות: שימו לב שמגיעים ל-20 נ\"ז בכל התואר.",
  "אם צריך למרוח את התואר, תעדפו קודם קורסים שחוסמים קורסים אחרים.",
];

export const SYSTEM_PLANNER_GUIDE = [
  {
    id: "year-a",
    label: "שנה א׳",
    semesters: [
      {
        id: "elul",
        label: "סמסטר אלול",
        courses: ["קדם מתמטיקה", "מבוא למחשבים"],
      },
      {
        id: "a",
        label: "סמסטר א׳",
        courses: [
          "אינפי 1",
          "לינארית א׳",
          "מבוא למדעי המחשב",
          "מערכות ספרתיות",
          "אנגלית",
        ],
      },
      {
        id: "b",
        label: "סמסטר ב׳",
        courses: [
          "אינפי 2",
          "לינארית ב׳",
          "מבנה נתונים א׳",
          "תכנות מתקדם (סדנה ב-C++)",
          "מבנה המחשב",
          "מעבדה במבנה המחשב",
          "אנגלית",
        ],
      },
    ],
  },
  {
    id: "year-b",
    label: "שנה ב׳",
    semesters: [
      {
        id: "elul",
        label: "סמסטר אלול",
        courses: ["הסתברות", "אנגלית"],
      },
      {
        id: "a",
        label: "סמסטר א׳",
        courses: [
          "לוגיקה",
          "בדידה",
          "מבנה נתונים ב׳",
          "מבוא להנדסת תוכנה",
          "סטטיסטיקה",
        ],
        recommendedElectives: 2,
        note: "מומלץ לקחת עוד 2 קורסי רשות.",
      },
      {
        id: "b",
        label: "סמסטר ב׳",
        courses: [
          "מיני פרויקט במבוא להנדסת תוכנה",
          "תכנות פונקציונלי ולוגי",
          "אוטומטים",
          "מבוא לתקשורת מחשבים",
          "מערכות הפעלה",
        ],
        recommendedElectives: 1,
        note: "מומלץ לקחת עוד קורס רשות.",
      },
    ],
  },
  {
    id: "year-c",
    label: "שנה ג׳",
    semesters: [
      {
        id: "elul",
        label: "סמסטר אלול",
        courses: ["אנגלית למדעי המחשב", "מחשוב ענן"],
        note: "במידה וניתן, מומלץ להוסיף עוד קורס.",
      },
      {
        id: "a",
        label: "סמסטר א׳",
        courses: ["בסיסי נתונים", "אלגוריתמים", "הנדסת תוכנה", "קומפיילרים"],
        recommendedElectives: 1,
        note: "מומלץ לקחת עוד קורס רשות.",
      },
      {
        id: "b",
        label: "סמסטר ב׳",
        courses: [
          "עקרונות",
          "חישוביות",
          "עיצוב ותכנות מונחה עצמים",
          "מיני פרויקט בבסיסי נתונים",
        ],
      },
    ],
  },
];

export const COURSES = [
  {
    name: "אינפי 1",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "מתמטיקה מורכבת, קושי של תחילת תואר.",
    effortNote: "תרגילי בית לוקחים הרבה זמן.",
  },
  {
    name: "לינארית א",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "מתמטיקה מורכבת, קושי של תחילת תואר.",
    effortNote: "תרגילי בית לוקחים יחסית זמן.",
  },
  {
    name: "מערכות ספרתיות",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "הקורס עצמו ממש קל. המבחן ממש קשה.",
    effortNote: "תרגילי בית, יחסית קלים.",
  },
  {
    name: "מבוא למדעי המחשב",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קוד, תחילת תואר, ולכן הכול מרגיש קשה יותר בהתחלה.",
    effortNote: "תרגילי בית דורשים השקעה.",
  },
  {
    name: "אינפי 2",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "המשך של אינפי, ולטעמי הרבה יותר קל מאינפי 1.",
    effortNote: "תרגילי בית, פחות זמן מאינפי 1.",
  },
  {
    name: "לינארית ב",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קורס קשה אבל בהחלט עביר.",
    effortNote: "תרגילי בית.",
  },
  {
    name: "סדנא ב-C++",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "המשך של מבוא למדמ״ח, קשה כי יש כמות גדולה של חומר.",
    effortNote: "תרגילי בית, דורש השקעה.",
  },
  {
    name: "מבנה המחשב",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קשה כי המבחן ממש מכשיל.",
    effortNote: "תרגילי בית.",
  },
  {
    name: "מבנה נתונים א׳",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קורס קשה, אם כי בעיני מעניין ממש.",
    effortNote: "תרגילי בית, דורש השקעה.",
  },
  {
    name: "מבנה נתונים ב׳",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קורס קשה, אם כי בעיני מעניין ממש.",
    effortNote: "תרגילי בית, דורש השקעה.",
  },
  {
    name: "לוגיקה",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קורס קל וחמוד. מבחן נוראי.",
    effortNote: "תרגילי בית, קלים יחסית.",
  },
  {
    name: "אוטומטים",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "מבחן של תרצה, ולכן נחשב קשה.",
    effortNote: "תרגילי בית יחסית קלים.",
  },
  {
    name: "ניתוח אלגוריתמים וסיבוכיות",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קורס קשה, אם כי בעיני מעניין ממש.",
    effortNote: "תרגילי בית, חשוב להשקיע זמן ללמידה ולהבנה.",
  },
  {
    name: "קומפיילרים ומתרגמים",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קורס קצת קשה להבנה, אבל יש בו הרבה טכניקה. ברגע שלומדים אותה מצליחים.",
    effortNote: "תרגילי בית, חשוב להשקיע זמן ללמידה ולהבנה.",
  },
  {
    name: "מבוא לתקשורת מחשבים",
    difficulty: "hard",
    requiresSemesterEffort: false,
    detail: "תלוי במבחן. בגדול הוא קשה כי זה הרבה חומר ללמוד.",
    effortNote: "יש רק 2 בחני אמצע.",
  },
  {
    name: "מערכות הפעלה",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "קורס כבד יחסית לאורך הדרך.",
    effortNote: "יש תרגילי בית.",
  },
  {
    name: "מיני פרויקט במערכת חלונות",
    difficulty: "hard",
    requiresSemesterEffort: true,
    detail: "זה קורס מאוד חשוב ומלמד אבל גם מאוד קשה.",
    effortNote: "דורש המון השקעה במהלך הסמסטר.",
  },
  {
    name: "מתמטיקה בדידה",
    difficulty: "medium",
    requiresSemesterEffort: true,
    detail: "קורס בסדר גמור למי שלומד כמו שצריך.",
    effortNote: "תרגילי בית יחסית קלים.",
  },
  {
    name: "סטטיסטיקה למהנדסים",
    difficulty: "medium",
    requiresSemesterEffort: true,
    detail: "בעיני זה אפילו קורס קל למי שלומד כמו שצריך.",
    effortNote: "תרגילי בית יחסית קלים.",
  },
  {
    name: "מבוא להנדסת תוכנה",
    difficulty: "medium",
    requiresSemesterEffort: false,
    detail: "קורס בינוני, עם עומס סביר כששומרים על קצב.",
    effortNote: "יחסית לא דורש יותר מדי השקעה במהלך הסמסטר.",
  },
  {
    name: "תכנות פונקציונלי ולוגי",
    difficulty: "medium",
    requiresSemesterEffort: true,
    detail: "קורס בינוני. מי שמבין תבניות ומתרגל מצליח.",
    effortNote: "תרגילי בית, לא דורשים יותר מדי זמן.",
  },
  {
    name: "משוואות דפרנציאליות",
    difficulty: "medium",
    requiresSemesterEffort: true,
    detail: "הקושי הוא לזכור הרבה תבניות ולדעת במה להשתמש ומתי.",
    effortNote: "יש תרגילי בית, חלקם ארוכים יחסית.",
  },
  {
    name: "בסיסי נתונים",
    difficulty: "medium",
    requiresSemesterEffort: false,
    detail: "תלוי במבחן. לפעמים הוא בסדר ולפעמים קשה. האמריקאי יחסית קל והחלק הפתוח קשה.",
    effortNote: "אין תרגילי בית. יש לפעמים בחנים.",
  },
  {
    name: "כריית מידע",
    difficulty: "medium",
    requiresSemesterEffort: false,
    detail: "חלק יגידו קשה, אבל בעיני זה המשך טבעי למבוא לבינה עבור מי שמתרגל אלגוריתמים.",
    effortNote: "כמעט ולא דורש במהלך הסמסטר.",
  },
  {
    name: "עקרונות שפות תוכנה",
    difficulty: "medium",
    requiresSemesterEffort: true,
    detail: "תלוי בשפה שנתנו לכם. יש אלמנט של מזל, אבל מי שמשקיע מצליח.",
    effortNote: "תרגילי בית יחסית דורשים השקעה, תלוי בקושי השפה.",
  },
  {
    name: "חישוביות ומורכבות החישובים",
    difficulty: "medium",
    requiresSemesterEffort: false,
    detail: "קורס קשה, אבל המפתח הוא ללמוד ולתרגל תוך כדי הסמסטר.",
    effortNote: "אין תרגילי בית, אבל חשוב ללמוד ולתרגל לאורך הסמסטר.",
  },
  {
    name: "עיצוב מונחה עצמים",
    difficulty: "medium",
    requiresSemesterEffort: true,
    detail: "קורס שנחשב קשה. החלק האמריקאי סביר אם מתרגלים, והחלק הפתוח קשה.",
    effortNote: "יש תרגילי בית.",
  },
  {
    name: "מעבדה במבנה המחשב",
    difficulty: "easy",
    requiresSemesterEffort: false,
    detail: "קורס קל יחסית.",
    effortNote: "לא דורש יותר מדי השקעה במהלך הסמסטר.",
  },
  {
    name: "הסתברות",
    difficulty: "easy",
    requiresSemesterEffort: true,
    detail: "מתמטיקה יותר נחמדה.",
    effortNote: "תרגילי בית יחסית קלים.",
  },
  {
    name: "הנדסת תוכנה",
    difficulty: "easy",
    requiresSemesterEffort: false,
    detail: "קורס יחסית קל, מצגות בעברית ומובנות. אין יותר מדי מה להסתבך.",
    effortNote: "אין תרגילי בית.",
  },
  {
    name: "מיני פרויקט בבסיסי נתונים",
    difficulty: "easy",
    requiresSemesterEffort: false,
    detail: "קורס נחמד ממש.",
    effortNote: "יש פרויקט, אבל הוא לא דורש יותר מדי זמן.",
  },
  {
    name: "מחשוב ענן",
    difficulty: "medium",
    requiresSemesterEffort: false,
    detail: "קורס ממש חשוב ומלמד.",
    effortNote: "לא דורש השקעה שוטפת — בסוף הסמסטר יש פרויקט להגשה.",
  },
  {
    name: "חשמל",
    difficulty: "easy",
    requiresSemesterEffort: true,
    detail: "קורס יחסית קל.",
    effortNote: "יש תרגילי בית יחסית קלים.",
  },
  {
    name: "מבוא לבינה מלאכותית",
    difficulty: "medium",
    requiresSemesterEffort: false,
    detail: "קורס מעניין ומלמד.",
    effortNote: "יש מעט תרגילי בית, לא דורש יותר מדי השקעה.",
  },
  {
    name: "מהשכלה לתעסוקה",
    difficulty: "easy",
    requiresSemesterEffort: false,
    detail: "קורס של 2 נ״ז, לא יותר מדי עומס.",
    effortNote: "יש מעט עבודות להגיש, לא דורש השקעה גדולה.",
  },
];